/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cci_mini_rpc_CONSTANTS_H
#define cci_mini_rpc_CONSTANTS_H

#include "cci_mini_rpc_types.h"



class cci_mini_rpcConstants {
 public:
  cci_mini_rpcConstants();

};

extern const cci_mini_rpcConstants g_cci_mini_rpc_constants;



#endif
