/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cci_mini_rpc_constants.h"



const cci_mini_rpcConstants g_cci_mini_rpc_constants;

cci_mini_rpcConstants::cci_mini_rpcConstants() {
}



