// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "cci_mini_clang_rpc.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class cci_mini_clang_rpcHandler : virtual public cci_mini_clang_rpcIf {
 public:
  cci_mini_clang_rpcHandler() {
    // Your initialization goes here
  }

  void perform_diag(std::string& _return, const std::string& index_module) {
    // Your implementation goes here
    printf("perform_diag\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<cci_mini_clang_rpcHandler> handler(new cci_mini_clang_rpcHandler());
  shared_ptr<TProcessor> processor(new cci_mini_clang_rpcProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

